export {
  ApiError,
  buildFileBrowserLaunchPlan,
  createCompatibilityCanvasSource,
  createCanvasSourceVersion,
  createCompatibilityGeneratedCanvasPath,
  createCompatibilityWorkspaceCanvas,
  createDefaultCanvasSource,
  createGeneratedCanvasPath,
  createWorkspaceCanvas,
  ensureWorkspaceRoot,
  normalizeWorkspaceRootPath,
  openWorkspaceInFileBrowser,
  probeWorkspace,
  requireWorkspaceRoot,
  resolveDefaultWorkspaceRootPath,
  resolveWorkspaceBrowserTargetPath,
  resolveCompatibilityCanvasPath,
  resolveWorkspaceCanvasPath,
  toWorkspaceRelativePath,
  type FileBrowserAction,
  type FileBrowserLaunchResult,
  type CompatibilityWorkspaceCanvasSummary,
  type WorkspaceCanvasSummary,
  type WorkspaceHealth,
  type WorkspaceHealthStatus,
  type WorkspaceProbeResult,
} from '../../../../libs/shared/src/lib/workspace-shell';
