export {
  ApiError,
  buildFileBrowserLaunchPlan,
  createCompatibilityDocumentSource,
  createDocumentSourceVersion,
  createCompatibilityGeneratedDocumentPath,
  createCompatibilityWorkspaceDocument,
  createDefaultDocumentSource,
  createGeneratedDocumentPath,
  createWorkspaceDocument,
  ensureWorkspaceRoot,
  normalizeWorkspaceRootPath,
  openWorkspaceInFileBrowser,
  probeWorkspace,
  requireWorkspaceRoot,
  resolveDefaultWorkspaceRootPath,
  resolveWorkspaceBrowserTargetPath,
  resolveCompatibilityDocumentPath,
  resolveWorkspaceDocumentPath,
  toWorkspaceRelativePath,
  type FileBrowserAction,
  type FileBrowserLaunchResult,
  type CompatibilityWorkspaceDocumentSummary,
  type WorkspaceDocumentSummary,
  type WorkspaceHealth,
  type WorkspaceHealthStatus,
  type WorkspaceProbeResult,
} from '../../../../libs/shared/src/lib/workspace-shell';
