export {
  ApiError,
  buildFileBrowserLaunchPlan,
  createCompatibilityCanvasSource,
  createCanvasSourceVersion,
  createDefaultCanvasSource,
  ensureWorkspaceRoot,
  normalizeWorkspaceRootPath,
  openWorkspaceInFileBrowser,
  probeWorkspace,
  requireWorkspaceRoot,
  resolveDefaultWorkspaceRootPath,
  resolveWorkspaceBrowserTargetPath,
  toWorkspaceRelativePath,
  type FileBrowserAction,
  type FileBrowserLaunchResult,
  type WorkspaceHealth,
  type WorkspaceHealthStatus,
  type WorkspaceProbeResult,
} from '../../../../libs/shared/src/lib/workspace-shell';
