// @vitest-environment jsdom

import type { ReactNode } from 'react';
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { AppProvider } from '../../../app/providers/AppProvider';
import { createBodyDocument, createBodyParagraphNode } from '../../../core/editor/model/editor-body';
import { useEditorStore } from '../../../core/editor/model/editor-store';
import { CanvasSelectionLayer } from './CanvasSelectionLayer';
import { CanvasViewport } from './CanvasViewport';

class ResizeObserverStub {
  observe() {}

  disconnect() {}

  unobserve() {}
}

function renderInProvider(children: ReactNode, root: Root) {
  act(() => {
    root.render(
      <AppProvider>
        {children}
      </AppProvider>,
    );
  });
}

describe('CanvasViewport document bodies', () => {
  let container: HTMLDivElement;
  let root: Root;

  beforeEach(() => {
    (globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
    globalThis.ResizeObserver = ResizeObserverStub as typeof ResizeObserver;
    window.matchMedia = window.matchMedia ?? (((query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addEventListener: () => {},
      removeEventListener: () => {},
      addListener: () => {},
      removeListener: () => {},
      dispatchEvent: () => false,
    })) as typeof window.matchMedia);
    useEditorStore.getState().reset();
    useEditorStore.getState().setViewportRect(1200, 800);
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(() => {
    act(() => {
      root.unmount();
    });
    container.remove();
  });

  it('renders seeded sticky document bodies without autogenerated canvas labels', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
    });

    expect(container.textContent).not.toContain('Sticky 1');
    expect(container.textContent).not.toContain('MARKDOWN');
    expect(container.textContent).not.toContain('Remove');
    expect(container.textContent).not.toContain('Select a block to insert after it');
  });

  it('renders seeded image nodes for image objects', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('image');
    });

    const image = container.querySelector('.canvas-object[data-kind="image"] img');
    expect(image).not.toBeNull();
    expect(image?.getAttribute('src')).toContain('data:image/svg+xml');
  });

  it('selects an object on first click and enters body edit on second click', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
    });

    const stickyNode = container.querySelector('.canvas-object[data-kind="sticky"]') as HTMLDivElement;
    expect(stickyNode).toBeTruthy();

    act(() => {
      useEditorStore.getState().clearSelection();
      stickyNode.dispatchEvent(new MouseEvent('pointerdown', { bubbles: true, button: 0 }));
      stickyNode.dispatchEvent(new MouseEvent('click', { bubbles: true, button: 0 }));
    });

    expect(useEditorStore.getState().selection.primaryId).toBe('sticky-1');
    expect(useEditorStore.getState().overlays.isBodyEditorOpen).toBe(false);

    const body = stickyNode.querySelector('.canvas-object__content-stack') as HTMLDivElement;
    act(() => {
      body.dispatchEvent(new MouseEvent('pointerdown', { bubbles: true, button: 0 }));
      body.dispatchEvent(new MouseEvent('click', { bubbles: true, button: 0 }));
    });

    expect(useEditorStore.getState().overlays.activeBodyEditorObjectId).toBe('sticky-1');
    expect(useEditorStore.getState().overlays.isBodyEditorOpen).toBe(true);
  });

  it('drags a selected object when the pointer starts on its body area', () => {
    renderInProvider(<CanvasViewport />, root);

    let stickyId = '';
    let initialX = 0;
    let initialY = 0;
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      stickyId = useEditorStore.getState().selection.primaryId!;
      const sticky = useEditorStore.getState().scene.objects.find((object) => object.id === stickyId)!;
      initialX = sticky.x;
      initialY = sticky.y;
    });

    const body = container.querySelector('.canvas-object[data-kind="sticky"] .canvas-object__content-stack') as HTMLDivElement;
    expect(body).toBeTruthy();

    act(() => {
      body.dispatchEvent(new MouseEvent('pointerdown', {
        bubbles: true,
        button: 0,
        clientX: 120,
        clientY: 120,
      }));
      window.dispatchEvent(new MouseEvent('pointermove', {
        bubbles: true,
        clientX: 156,
        clientY: 144,
      }));
      window.dispatchEvent(new MouseEvent('pointerup', {
        bubbles: true,
        clientX: 156,
        clientY: 144,
      }));
    });

    const sticky = useEditorStore.getState().scene.objects.find((object) => object.id === stickyId)!;
    expect(sticky.x).not.toBe(initialX);
    expect(sticky.y).not.toBe(initialY);
    expect(useEditorStore.getState().overlays.isBodyEditorOpen).toBe(false);
  });

  it('commits document body edits when focus leaves the inline editor', () => {
    renderInProvider(
      <>
        <button data-testid="outside" type="button">Outside</button>
        <CanvasViewport />
      </>,
      root,
    );

    let stickyId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      stickyId = useEditorStore.getState().selection.primaryId!;
      useEditorStore.getState().openBodyEditor(stickyId);
    });

    const editor = container.querySelector('.canvas-object__wysiwyg-surface') as HTMLDivElement;
    const outsideButton = container.querySelector('[data-testid="outside"]') as HTMLButtonElement;
    expect(editor).toBeTruthy();
    act(() => {
      editor.focus();
      useEditorStore.getState().updateBodyEditorDraft(stickyId, createBodyDocument([
        {
          type: 'heading',
          attrs: { level: 1 },
          content: [{ type: 'text', text: 'Launch plan' }],
        },
        createBodyParagraphNode(),
      ]));
    });
    act(() => {
      outsideButton.focus();
    });

    const sticky = useEditorStore.getState().scene.objects.find((object) => object.id === stickyId)!;
    expect(sticky.body.content[0]).toEqual(expect.objectContaining({
      type: 'heading',
      attrs: expect.objectContaining({ level: 1 }),
    }));
    expect(useEditorStore.getState().overlays.activeBodyEditorObjectId).toBeNull();
  });

  it('commits the active draft before selecting another object', () => {
    renderInProvider(<CanvasViewport />, root);

    let firstId = '';
    let secondId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      firstId = useEditorStore.getState().selection.primaryId!;
      useEditorStore.getState().createObjectAtViewportCenter('shape');
      secondId = useEditorStore.getState().selection.primaryId!;
      useEditorStore.getState().selectOnly(firstId);
      useEditorStore.getState().openBodyEditor(firstId);
      useEditorStore.getState().updateBodyEditorDraft(firstId, createBodyDocument([
        createBodyParagraphNode('persist me'),
      ]));
    });

    const shapeNode = container.querySelector('.canvas-object[data-kind="shape"]') as HTMLDivElement;
    expect(shapeNode).toBeTruthy();

    act(() => {
      shapeNode.dispatchEvent(new MouseEvent('pointerdown', { bubbles: true, button: 0 }));
    });

    expect(useEditorStore.getState().selection.primaryId).toBe(secondId);
    expect(useEditorStore.getState().scene.objects.find((object) => object.id === firstId)?.body.content[0])
      .toEqual(expect.objectContaining({
        type: 'paragraph',
        content: [{ type: 'text', text: 'persist me' }],
      }));
    expect(useEditorStore.getState().overlays.isBodyEditorOpen).toBe(false);
  });

  it('renders resize and rotate handles for single and multi selection', () => {
    renderInProvider(
      <>
        <CanvasViewport />
        <CanvasSelectionLayer />
      </>,
      root,
    );

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('shape');
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(8);
    expect(container.querySelector('[data-testid="graph-canvas-rotate-handle"]')).toBeTruthy();

    let firstId = useEditorStore.getState().selection.primaryId!;
    let secondId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      secondId = useEditorStore.getState().selection.primaryId!;
      useEditorStore.getState().selectMany([firstId, secondId], secondId);
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(8);
    expect(container.textContent).toContain('2 selected');
  });

  it('renders style previews on floating triggers and opens fill and border drawers', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('shape');
      useEditorStore.getState().togglePanel('inspector');
    });

    expect(container.querySelectorAll('.floating-object-menu__trigger')).toHaveLength(4);
    expect(container.querySelector('.floating-object-menu__swatch-preview')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__outline-preview')).toBeTruthy();

    const fillButton = container.querySelector('[aria-label="채우기"]') as HTMLButtonElement;
    expect(fillButton).toBeTruthy();

    act(() => {
      fillButton.click();
    });

    expect(fillButton.getAttribute('aria-expanded')).toBe('true');
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__swatch-grid')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__hex-input')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__title')).toBeNull();

    const borderButton = container.querySelector('[aria-label="테두리"]') as HTMLButtonElement;
    expect(borderButton).toBeTruthy();

    act(() => {
      borderButton.click();
    });

    expect(borderButton.getAttribute('aria-expanded')).toBe('true');
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__preset-row')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__hex-input')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__title')).toBeNull();

    const moreButton = container.querySelector('[aria-label="더보기"]') as HTMLButtonElement;
    expect(moreButton).toBeTruthy();

    act(() => {
      moreButton.click();
    });

    const inspectorButton = container.querySelector('[aria-label="인스펙터 열기"]') as HTMLButtonElement;
    expect(inspectorButton).toBeTruthy();
    expect(useEditorStore.getState().panels.open.inspector).toBe(false);

    act(() => {
      inspectorButton.click();
    });

    expect(useEditorStore.getState().panels.open.inspector).toBe(true);

    const shapeNode = container.querySelector('.canvas-object[data-kind="shape"]') as HTMLDivElement;
    expect(shapeNode).toBeTruthy();

    act(() => {
      shapeNode.dispatchEvent(new MouseEvent('contextmenu', {
        bubbles: true,
        cancelable: true,
        clientX: 48,
        clientY: 48,
      }));
    });

    expect(container.textContent).toContain('복사');
    expect(container.textContent).toContain('붙여넣기');
    expect(container.textContent).toContain('삭제');
    expect(container.textContent).toContain('맨앞으로');
    expect(container.textContent).toContain('앞으로');
    expect(container.textContent).toContain('뒤로');
    expect(container.textContent).toContain('맨뒤로');
  });

  it('commits the active draft before opening floating fill controls', () => {
    renderInProvider(<CanvasViewport />, root);

    let stickyId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      stickyId = useEditorStore.getState().selection.primaryId!;
      useEditorStore.getState().openBodyEditor(stickyId);
      useEditorStore.getState().updateBodyEditorDraft(stickyId, createBodyDocument([
        createBodyParagraphNode('keep this'),
      ]));
    });

    const fillButton = container.querySelector('[aria-label="채우기"]') as HTMLButtonElement;
    expect(fillButton).toBeTruthy();

    act(() => {
      fillButton.click();
    });

    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__swatch-grid')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__drawer .object-style-editor__title')).toBeNull();
    expect(useEditorStore.getState().scene.objects.find((object) => object.id === stickyId)?.body.content[0])
      .toEqual(expect.objectContaining({
        type: 'paragraph',
        content: [{ type: 'text', text: 'keep this' }],
      }));
    expect(useEditorStore.getState().overlays.isBodyEditorOpen).toBe(false);
  });

  it('hides transform handles while context menu or body editor is open', () => {
    renderInProvider(
      <>
        <CanvasViewport />
        <CanvasSelectionLayer />
      </>,
      root,
    );

    let stickyId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      stickyId = useEditorStore.getState().selection.primaryId!;
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(8);

    act(() => {
      useEditorStore.getState().setContextMenu({
        objectId: stickyId,
        x: 24,
        y: 24,
      });
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(0);

    act(() => {
      useEditorStore.getState().setContextMenu(null);
      useEditorStore.getState().openBodyEditor(stickyId);
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(0);
    expect(container.querySelector('[data-testid="graph-canvas-rotate-handle"]')).toBeNull();
  });
});
