// @vitest-environment jsdom

import type { ReactNode } from 'react';
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { AppProvider } from '../../../app/providers/AppProvider';
import { useEditorStore } from '../../../core/editor/model/editor-store';
import { CanvasSelectionLayer } from './CanvasSelectionLayer';
import { CanvasViewport } from './CanvasViewport';

class ResizeObserverStub {
  observe() {}

  disconnect() {}

  unobserve() {}
}

function renderInProvider(children: ReactNode, root: Root) {
  act(() => {
    root.render(
      <AppProvider>
        {children}
      </AppProvider>,
    );
  });
}

describe('CanvasViewport content blocks', () => {
  let container: HTMLDivElement;
  let root: Root;

  beforeEach(() => {
    (globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
    globalThis.ResizeObserver = ResizeObserverStub as typeof ResizeObserver;
    window.matchMedia = window.matchMedia ?? (((query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addEventListener: () => {},
      removeEventListener: () => {},
      addListener: () => {},
      removeListener: () => {},
      dispatchEvent: () => false,
    })) as typeof window.matchMedia);
    useEditorStore.getState().reset();
    useEditorStore.getState().setViewportRect(1200, 800);
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(() => {
    act(() => {
      root.unmount();
    });
    container.remove();
  });

  it('renders seeded sticky markdown blocks without autogenerated canvas labels', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
    });

    expect(container.textContent).not.toContain('Sticky 1');
    expect(container.textContent).not.toContain('MARKDOWN');
    expect(container.textContent).not.toContain('Remove');
    expect(container.textContent).not.toContain('Select a block to insert after it');
  });

  it('renders seeded image blocks for image objects', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('image');
    });

    const image = container.querySelector('.canvas-object[data-kind="image"] img');
    expect(image).not.toBeNull();
    expect(image?.getAttribute('src')).toContain('data:image/svg+xml');
  });

  it('commits markdown block edits when focus leaves the inline editor', () => {
    renderInProvider(
      <>
        <button data-testid="outside" type="button">Outside</button>
        <CanvasViewport />
      </>,
      root,
    );

    let stickyId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      stickyId = useEditorStore.getState().selection.primaryId!;
      const firstBlockId = useEditorStore.getState().scene.objects
        .find((object) => object.id === stickyId)!
        .contentBlocks[0]!.id;
      useEditorStore.getState().startBlockEdit(stickyId, firstBlockId);
    });

    const editor = container.querySelector('.canvas-object__wysiwyg-surface') as HTMLDivElement;
    const outsideButton = container.querySelector('[data-testid="outside"]') as HTMLButtonElement;

    expect(editor).toBeTruthy();
    act(() => {
      editor.focus();
      editor.innerHTML = '<h1>Launch plan</h1>';
      editor.dispatchEvent(new Event('input', { bubbles: true }));
    });
    act(() => {
      outsideButton.focus();
    });

    const sticky = useEditorStore.getState().scene.objects.find((object) => object.id === stickyId)!;
    expect(sticky.contentBlocks[0]).toEqual(expect.objectContaining({ source: '# Launch plan' }));
    expect(useEditorStore.getState().overlays.blockEditor).toBeNull();
  });

  it('renders resize and rotate handles for single and multi selection', () => {
    renderInProvider(
      <>
        <CanvasViewport />
        <CanvasSelectionLayer />
      </>,
      root,
    );

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('shape');
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(8);
    expect(container.querySelector('[data-testid="graph-canvas-rotate-handle"]')).toBeTruthy();

    let firstId = useEditorStore.getState().selection.primaryId!;
    let secondId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      secondId = useEditorStore.getState().selection.primaryId!;
      useEditorStore.getState().selectMany([firstId, secondId], secondId);
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(8);
    expect(container.textContent).toContain('2 selected');
  });

  it('renders style previews on floating triggers and routes fill changes to inspector focus', () => {
    renderInProvider(<CanvasViewport />, root);

    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('shape');
    });

    expect(container.querySelectorAll('.floating-object-menu__trigger')).toHaveLength(4);
    expect(container.querySelector('.floating-object-menu__swatch-preview')).toBeTruthy();
    expect(container.querySelector('.floating-object-menu__outline-preview')).toBeTruthy();

    const fillButton = container.querySelector('[aria-label="채우기"]') as HTMLButtonElement;
    expect(fillButton).toBeTruthy();

    act(() => {
      fillButton.click();
    });

    expect(useEditorStore.getState().overlays.focusRequest?.field).toBe('fill');
    expect(useEditorStore.getState().panels.open.inspector).toBe(true);

    const moreButton = container.querySelector('[aria-label="더보기"]') as HTMLButtonElement;
    expect(moreButton).toBeTruthy();

    act(() => {
      moreButton.click();
    });

    const textContent = container.textContent ?? '';
    expect(textContent.indexOf('복사')).toBeLessThan(textContent.indexOf('삭제'));
    expect(textContent.indexOf('삭제')).toBeLessThan(textContent.indexOf('맨앞으로'));

    const shapeNode = container.querySelector('.canvas-object[data-kind="shape"]') as HTMLDivElement;
    expect(shapeNode).toBeTruthy();

    act(() => {
      shapeNode.dispatchEvent(new MouseEvent('contextmenu', {
        bubbles: true,
        cancelable: true,
        clientX: 48,
        clientY: 48,
      }));
    });

    expect(container.textContent).toContain('복사');
    expect(container.textContent).toContain('붙여넣기');
    expect(container.textContent).toContain('삭제');
    expect(container.textContent).toContain('맨앞으로');
    expect(container.textContent).toContain('앞으로');
    expect(container.textContent).toContain('뒤로');
    expect(container.textContent).toContain('맨뒤로');
  });

  it('hides transform handles while context menu or block editor is open', () => {
    renderInProvider(
      <>
        <CanvasViewport />
        <CanvasSelectionLayer />
      </>,
      root,
    );

    let stickyId = '';
    act(() => {
      useEditorStore.getState().createObjectAtViewportCenter('sticky');
      stickyId = useEditorStore.getState().selection.primaryId!;
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(8);

    act(() => {
      useEditorStore.getState().setContextMenu({
        objectId: stickyId,
        x: 24,
        y: 24,
      });
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(0);

    act(() => {
      useEditorStore.getState().setContextMenu(null);
      const firstBlockId = useEditorStore.getState().scene.objects
        .find((object) => object.id === stickyId)!
        .contentBlocks[0]!.id;
      useEditorStore.getState().startBlockEdit(stickyId, firstBlockId);
    });

    expect(container.querySelectorAll('[data-testid="graph-canvas-resize-handle"]')).toHaveLength(0);
    expect(container.querySelector('[data-testid="graph-canvas-rotate-handle"]')).toBeNull();
  });
});
